New heuristic, experiments, and refactoring
pszufe/LTMSim.jl pull request #1
Opened 2021-03-26 09:34 UTC by alessant

* Addition of the SubTSS heuristic
* Addition of the optimization procedure
* Experiments run for the journal extension of the WAW20 paper
* Results and plots
* Code refactoring and cleaning

Alessia, Carmine, and Gennaro

2021-03-26 14:50 UTC, pszufe requested changes
Looks great to me! I put some comments regarding code style that are just for reading. However, please add a single comment line to each experiment file.

2021-03-26 14:50 UTC, pszufe commented on src/experiments/benchmark_randV_randE.jl
> +push!(data, "BinarySearch(H)"=>Vector{Vector{Float64}}())
Just note that shorter form is `Vector{Float64}[]`   (no need to be corrected)

2021-03-26 14:50 UTC, pszufe commented on src/experiments/benchmark_randV_randE.jl
> +    push!(data["SubTSS(H)-noOpt"], [r[12] for r in results])
There is something wrong with numbering - you are producing `r1...r8` and collecting `r[1:4]` and `r[9:12]`. Does this code work?

2021-03-26 14:50 UTC, pszufe commented on src/experiments/benchmark_randV_randE.jl
> +    results = @distributed (append!) for run=1:runs
This code could be nicer by collecting results to a `DataFrame` and having all those function you have here in a `Vector` rather than calling several lines that is v = `[greedy_tss_2section, bisect, greedy_tss, sub_tss]`. If you have any Julia function say `f` you can always do `Symbol(f)` and then simply store such symbols within a `DataFrame`. In this scenario `append!` would be just appending rows to a `DataFrame`. This is just a comment for the future - we do not need to do it now if the code works.

2021-03-26 14:50 UTC, pszufe commented on src/experiments/benchmark_randV_randE.jl
> +using Pkg, Distributed
Each experiment file needs one sentence explaining what the experiment does.

2021-03-26 14:50 UTC, pszufe commented on src/experiments/plot/proportionalV.jl
> +using Pkg
Each experiment file needs one sentence explaining what the experiment does.

2021-03-26 14:50 UTC, pszufe commented on src/experiments/plot/randomV.jl
> +using Pkg
Each experiment file needs one sentence explaining what the experiment does.

2021-03-26 14:50 UTC, pszufe commented on src/experiments/propV_propE05.jl
> +using Pkg, Distributed
Each experiment file needs one sentence explaining what the experiment does.

2021-03-26 14:50 UTC, pszufe commented on src/experiments/benchmark_randV_randE.jl
> +addprocs(4)
For production or distributing code it would be much better to give user a manual that shee needs to start julia with `-p` parameter such as:
```
julia -p 4 benchmark_randV_randE.jl
```
In this way they do not need to edit the code when changing the number of processes. Also this would give the user a flexibility to use ` --machine-file` startup parameter instead.

2021-03-26 14:50 UTC, pszufe commented on src/experiments/propV_randE.jl
> +using Pkg, Distributed
Each experiment file needs one sentence explaining what the experiment does.

2021-03-26 14:50 UTC, pszufe commented on src/experiments/randV_propE05.jl
> +using Pkg, Distributed
Each experiment file needs one sentence explaining what the experiment does.

2021-03-26 14:50 UTC, pszufe commented on src/experiments/randV_randE.jl
> +using Pkg, Distributed
Each experiment file needs one sentence explaining what the experiment does.

2021-03-26 14:50 UTC, pszufe commented on src/experiments/stats.jl
> +using Pkg
Each experiment file needs one sentence explaining what the experiment does.

2021-03-26 14:50 UTC, pszufe commented on src/heuristics/additive.jl
> +        location = Int(ceil( (left + right)/2))
better:
```
location = ceil(Int, (left + right)/2))
```
However if the code works do not change it now.

2021-03-26 14:50 UTC, pszufe commented on src/heuristics/additive.jl
> +                 if !haskey(U,nv.first) || nv.first in visited
Shorter form
```
(!haskey(U,nv.first) || nv.first in visited) && continue
```

2021-03-29 11:41 UTC, alessant commented on src/experiments/benchmark_randV_randE.jl
> +addprocs(4)
I have commented on this point on the README.md file and removed `addprocs()` in the scripts. Should I add anything else?

2021-03-29 11:43 UTC, pszufe approved these changes

2021-03-29 11:43 UTC, merged

2021-03-29 11:46 UTC, alessant commented on src/experiments/benchmark_randV_randE.jl
> +push!(data, "BinarySearch(H)"=>Vector{Vector{Float64}}())
Thanks for pointing that out. I have modified it as the code improved in readability, but - if we want - I can restore the original initialization.